<a href="https://colab.research.google.com/github/rico-1818/-classificacao/blob/main/regress%C3%A3o_aula08.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Treinamento do modelo de regressão

In [7]:
import pandas  as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split

#Regressão linear
from sklearn.linear_model import LinearRegression
#regressão polinomial
from sklearn.preprocessing import PolynomialFeatures

#metricas
from sklearn.metrics import r2_score
from sklearn.metrics import mean_absolute_error

In [8]:
df = pd.read_excel('https://github.com/rico-1818/-classificacao/raw/refs/heads/main/concrete+compressive+strength/Concrete_Data.xls')
df.head()

,Cement (component 1)(kg in a m^3 mixture),Blast Furnace Slag (component 2)(kg in a m^3 mixture),Fly Ash (component 3)(kg in a m^3 mixture),Water (component 4)(kg in a m^3 mixture),Superplasticizer (component 5)(kg in a m^3 mixture),Coarse Aggregate (component 6)(kg in a m^3 mixture),Fine Aggregate (component 7)(kg in a m^3 mixture),Age (day),"Concrete compressive strength(MPa, megapascals)"
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1030 entries, 0 to 1029
Data columns (total 9 columns):
 #   Column                                                 Non-Null Count  Dtype
---  ------                                                 --------------  -----
 0   Cement (component 1)(kg in a m^3 mixture)              1030 non-null   float64
 1   Blast Furnace Slag (component 2)(kg in a m^3 mixture)  1030 non-null   float64
 2   Fly Ash (component 3)(kg in a m^3 mixture)             1030 non-null   float64
 3   Water  (component 4)(kg in a m^3 mixture)              1030 non-null   float64
 4   Superplasticizer (component 5)(kg in a m^3 mixture)    1030 non-null   float64
 5   Coarse Aggregate  (component 6)(kg in a m^3 mixture)   1030 non-null   float64
 6   Fine Aggregate (component 7)(kg in a m^3 mixture)      1030 non-null   float64
 7   Age (day)                                              1030 non-null   int64
 8   Concrete compressive strength(MPa, megapascals)        1030 non-null   float64
dtypes: float64(8), int64(1)
memory usage: 72.6 KB

In [10]:
df = df.rename(columns={
    'Cement (component 1)(kg in a m^3 mixture)': 'Cimento',
    'Blast Furnace Slag (component 2)(kg in a m^3 mixture)': 'Escória de Alto Forno',
    'Fly Ash (component 3)(kg in a m^3 mixture)': 'Cinza Volante',
    'Water  (component 4)(kg in a m^3 mixture)': 'Água',
    'Superplasticizer (component 5)(kg in a m^3 mixture)': 'Superplastificante',
    'Coarse Aggregate  (component 6)(kg in a m^3 mixture)': 'Agregado Graúdo',
    'Fine Aggregate (component 7)(kg in a m^3 mixture)': 'Agregado Fino',
    'Age (day)': 'Idade (dias)',
    'Concrete compressive strength(MPa, megapascals)': 'Resistência à Compressão'
})
df.head()
df.columns.tolist()

,Cimento,Escória de Alto Forno,Cinza Volante,Água,Superplastificante,Agregado Graúdo,Agregado Fino,Idade (dias),"Concrete compressive strength(MPa, megapascals)"
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075

In [11]:
# target(y): concrete compressive strength
# todas(x): atributos com maior correleção com y

In [12]:
matriz_corr = df.corr()
matriz_corr

,Cimento,Escória de Alto Forno,Cinza Volante,Água,Superplastificante,Agregado Graúdo,Agregado Fino,Idade (dias),"Concrete compressive strength(MPa, megapascals)"
Cimento,1.000000,-0.275193,-0.397475,-0.081544,0.092771,-0.109356,-0.222720,0.081947,0.497833
Escória de Alto Forno,-0.275193,1.000000,-0.323569,0.107286,0.043376,-0.283998,-0.281593,-0.044246,0.134824
Cinza Volante,-0.397475,-0.323569,1.000000,-0.257044,0.377340,-0.009977,0.079076,-0.154370,-0.105753
Água,-0.081544,0.107286,-0.257044,1.000000,-0.657464,-0.182312,-0.450635,0.277604,-0.289613
Superplastificante,0.092771,0.043376,0.377340,-0.657464,1.000000,-0.266303,0.222501,-0.192717,0.366102
Agregado Graúdo,-0.109356,-0.283998,-0.009977,-0.182312,-0.266303,1.000000,-0.178506,-0.003016,-0.164928
Agregado Fino,-0.222720,-0.281593,0.079076,-0.450635,0.222501,-0.178506,1.000000,-0.156094,-0.167249
Idade (dias),0.081947,-0.044246,-0.154370,0.277604,-0.192717,-0.003016,-0.156094,1.000000,0.328877
"Concrete compressive strength(MPa, megapascals)",0.497833,0.134824,-0.105753,-0.289613,0.366102,-0.164928,-0.167249,0.328877,1.000000